jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Docker version
        run: docker --version

      - name: Check Docker Compose version
        run: docker compose version

      - name: Validate compose file
        run: docker compose -f docker/docker-compose.yml config

      - name: Start stack
        run: |
          cd docker
          docker compose up -d
          sleep 25

      - name: Check containers
        run: docker ps

      - name: Show logs
        run: |
          docker logs prometheus || true
          docker logs grafana || true

      - name: Cleanup
        run: |
          cd docker
          docker compose down
