name: 🚀 DevOps CI/CD Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:   # 👈 manual trigger added

jobs:

  validate:
    name: 🔍 Validate Project
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐳 Install Docker Compose
        run: |
          sudo apt update
          sudo apt install -y docker-compose

      - name: ✅ Validate docker-compose.yml
        run: docker-compose -f docker/docker-compose.yml config

      - name: 📁 Check Required Files
        run: |
          test -f docker/prometheus.yml
          test -f docker/alertmanager.yml
          test -f docker/alert.rules.yml

  test-stack:
    name: 🧪 Run Monitoring Stack
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐳 Start Stack
        run: |
          cd docker
          docker-compose up -d
          sleep 15
          docker ps

      - name: 🌐 Test Prometheus Endpoint
        run: curl -f http://localhost:9090 || exit 1

      - name: 🌐 Test Grafana Endpoint
        run: curl -f http://localhost:3000 || exit 1

      - name: 🧹 Cleanup
        run: |
          cd docker
          docker-compose down
